version: "3.8"
services:
  validator:
    image: ethereum/client-go:latest
    container_name: geth-validator
    working_dir: /root
    volumes:
      - ./validator:/root
      - ./genesis.json:/root/genesis.json
    command: 
      - geth
      - init
      - /root/genesis.json
      - --datadir
      - /root
    entrypoint: ""
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    networks:
      - ethereum

  node1:
    image: ethereum/client-go:latest
    container_name: geth-node1
    working_dir: /root
    volumes:
      - ./node1:/root
      - ./genesis.json:/root/genesis.json
    command:
      - geth
      - init
      - /root/genesis.json
      - --datadir
      - /root
    entrypoint: ""
    ports:
      - "8547:8545"
      - "8548:8546"
      - "30304:30303"
    networks:
      - ethereum

  node2:
    image: ethereum/client-go:latest
    container_name: geth-node2
    working_dir: /root
    volumes:
      - ./node2:/root
      - ./genesis.json:/root/genesis.json
    command:
      - geth
      - init
      - /root/genesis.json
      - --datadir
      - /root
    entrypoint: ""
    ports:
      - "8549:8545"
      - "8550:8546"
      - "30305:30303"
    networks:
      - ethereum

networks:
  ethereum:
    driver: bridge 